# Generated by Django 3.1.4 on 2020-12-15 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=100)),
                ('item_description', models.TextField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('item_active', models.BooleanField()),
                ('menu_sections', models.CharField(choices=[('Appetizers', 'Appetizers'), ('Shellfish', 'Shellfish'), ('Salads', 'Salads'), ('Entrees', 'Entrees'), ('Prime Steaks', 'Prime Steaks'), ('Large Format Steak', 'Large Format Steak'), ('Sides', 'Sides')], max_length=200, null=True)),
            ],
            options={
                'verbose_name_plural': 'Menu Item',
            },
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu_name', models.CharField(max_length=100)),
                ('menu_description', models.TextField(blank=True, null=True)),
                ('active', models.BooleanField()),
                ('menu_item_names', models.ManyToManyField(blank=True, null=True, to='resto.MenuItem')),
            ],
            options={
                'verbose_name_plural': 'Menu',
            },
        ),
    ]
