# Generated by Django 3.1.4 on 2020-12-14 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=100)),
                ('item_description', models.TextField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('item_active', models.BooleanField()),
            ],
            options={
                'verbose_name': 'Menu Item',
            },
        ),
        migrations.CreateModel(
            name='MenuSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_name', models.CharField(max_length=100)),
                ('section_description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Menu Section',
            },
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu_name', models.CharField(max_length=100)),
                ('menu_description', models.TextField(blank=True, null=True)),
                ('active', models.BooleanField()),
                ('menu_item_name', models.ManyToManyField(null=True, to='resto.MenuItem')),
                ('menu_section_name', models.ManyToManyField(null=True, to='resto.MenuSection')),
            ],
            options={
                'verbose_name': 'Menu',
            },
        ),
    ]
