# Generated by Django 3.1.4 on 2020-12-14 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resto', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='menu_item_name',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='menu_section_name',
        ),
        migrations.AddField(
            model_name='menu',
            name='menu_item_names',
            field=models.ManyToManyField(to='resto.MenuItem'),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='menu_sections',
            field=models.CharField(choices=[('Appetizers', 'Appetizers'), ('Shellfish', 'Shellfish'), ('Salads', 'Salads'), ('Entrees', 'Entrees'), ('Prime Steaks', 'Prime Steaks'), ('Large Format Steak', 'Large Format Steak'), ('Sides', 'Sides')], max_length=200, null=True),
        ),
        migrations.DeleteModel(
            name='MenuSection',
        ),
    ]
