# Generated by Django 3.1.4 on 2020-12-11 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resto', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menu',
            options={'verbose_name': 'Menu'},
        ),
        migrations.AlterModelOptions(
            name='menuitem',
            options={'verbose_name': 'Menu Item'},
        ),
        migrations.AlterModelOptions(
            name='menusection',
            options={'verbose_name': 'Menu Section'},
        ),
        migrations.RenameField(
            model_name='menu',
            old_name='menu_status',
            new_name='active',
        ),
        migrations.RenameField(
            model_name='menuitem',
            old_name='item_status',
            new_name='item_active',
        ),
    ]
