# Generated by Django 3.1.4 on 2021-01-12 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resto', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menuitem',
            old_name='menu_section1',
            new_name='menu_section',
        ),
    ]
