# Generated by Django 3.1.4 on 2020-12-18 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resto', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menu',
            old_name='menu_item_names',
            new_name='menu_item_name',
        ),
        migrations.RenameField(
            model_name='menu',
            old_name='menu_section_name',
            new_name='menu_type',
        ),
        migrations.RenameField(
            model_name='menuitem',
            old_name='menu_sections',
            new_name='menu_section',
        ),
        migrations.AddField(
            model_name='menuitem',
            name='menu_type',
            field=models.CharField(choices=[('Breakfast', 'Breakfast'), ('Brunch', 'Brunch'), ('Lunch', 'Lunch'), ('Dinner', 'Dinner')], max_length=100, null=True),
        ),
    ]
