# Generated by Django 3.1.4 on 2020-12-14 17:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resto', '0002_auto_20201214_1659'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='menu_item_names',
        ),
        migrations.AddField(
            model_name='menu',
            name='menu_item_names',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='resto.menuitem'),
        ),
    ]
