# Generated by Django 3.1.4 on 2021-01-12 23:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resto', '0002_auto_20210112_2159'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menusection',
            name='menus',
        ),
        migrations.CreateModel(
            name='FullMenu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='full_menu', to='resto.menu')),
                ('menu_item_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='full_menu_item', to='resto.menuitem')),
                ('menu_section_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='full_menu_section', to='resto.menusection')),
            ],
        ),
        migrations.AddField(
            model_name='menuitem',
            name='actual_menu',
            field=models.ManyToManyField(through='resto.FullMenu', to='resto.MenuSection'),
        ),
    ]
