# Generated by Django 3.1.4 on 2020-12-14 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resto', '0003_auto_20201214_1706'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='menu_item_names',
        ),
        migrations.AddField(
            model_name='menu',
            name='menu_item_names',
            field=models.ManyToManyField(to='resto.MenuItem'),
        ),
    ]
