# Generated by Django 3.1.4 on 2021-01-12 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resto', '0003_auto_20210112_2338'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuitem',
            name='actual_menu',
        ),
        migrations.AddField(
            model_name='menusection',
            name='menus',
            field=models.ManyToManyField(blank=True, null=True, to='resto.Menu'),
        ),
    ]
