# Generated by Django 3.1.4 on 2021-01-13 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resto', '0004_auto_20210112_2356'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuitem',
            name='menu_section',
        ),
        migrations.AddField(
            model_name='menusection',
            name='menu_items',
            field=models.ManyToManyField(blank=True, null=True, to='resto.MenuItem'),
        ),
    ]
