# Generated by Django 3.1.4 on 2020-12-14 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resto', '0004_auto_20201214_1709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
