# Generated by Django 3.1.4 on 2021-01-13 00:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resto', '0005_auto_20210113_0015'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FullMenu',
        ),
    ]
