# Generated by Django 3.1.4 on 2020-12-14 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resto', '0005_auto_20201214_1759'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menu',
            options={'verbose_name_plural': 'Menu'},
        ),
        migrations.AlterModelOptions(
            name='menuitem',
            options={'verbose_name_plural': 'Menu Item'},
        ),
        migrations.AlterField(
            model_name='menu',
            name='active',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='menu',
            name='menu_item_names',
            field=models.ManyToManyField(blank=True, null=True, to='resto.MenuItem'),
        ),
    ]
